2025-07-30 16:31:43.501 Uncaught exception GET /_stcore/stream (127.0.0.1)

HTTPServerRequest(protocol='http', host='civitasapp-txs6vtyryhh6pcjtgaqcmd.streamlit.app', method='GET', uri='/_stcore/stream', version='HTTP/1.1', remote_ip='127.0.0.1')

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/web/bootstrap.py", line 348, in run

    if asyncio.get_running_loop().is_running():

       ~~~~~~~~~~~~~~~~~~~~~~~~^^

RuntimeError: no running event loop


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/tornado/websocket.py", line 965, in _accept_connection

    open_result = handler.open(*handler.open_args, **handler.open_kwargs)

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/web/server/browser_websocket_handler.py", line 183, in open

    self._session_id = self._runtime.connect_session(

                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

        client=self,

        ^^^^^^^^^^^^

        user_info=user_info,

        ^^^^^^^^^^^^^^^^^^^^

        existing_session_id=existing_session_id,

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/runtime.py", line 386, in connect_session

    session_id = self._session_mgr.connect_session(

        client=client,

    ...<3 lines>...

        session_id_override=session_id_override,

    )

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/websocket_session_manager.py", line 101, in connect_session

    session = AppSession(

        script_data=script_data,

    ...<4 lines>...

        session_id_override=session_id_override,

    )

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/app_session.py", line 158, in __init__

    self.register_file_watchers()

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/app_session.py", line 195, in register_file_watchers

    self._local_sources_watcher = LocalSourcesWatcher(self._pages_manager)

                                  ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/watcher/local_sources_watcher.py", line 66, in __init__

    self.update_watched_pages()

    ~~~~~~~~~~~~~~~~~~~~~~~~~^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/watcher/local_sources_watcher.py", line 78, in update_watched_pages

    self._register_watcher(

    ~~~~~~~~~~~~~~~~~~~~~~^

        page_info["script_path"],

        ^^^^^^^^^^^^^^^^^^^^^^^^^

        module_name=None,

        ^^^^^^^^^^^^^^^^^

    )

    ^

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/watcher/local_sources_watcher.py", line 168, in _register_watcher

    watcher=PathWatcher(

            ~~~~~~~~~~~^

        filepath,

        ^^^^^^^^^

    ...<2 lines>...

        allow_nonexistent=False,

        ^^^^^^^^^^^^^^^^^^^^^^^^

    ),

    ^

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/watcher/event_based_path_watcher.py", line 107, in __init__

    path_watcher.watch_path(

    ~~~~~~~~~~~~~~~~~~~~~~~^

        self._path,

        ^^^^^^^^^^^

    ...<2 lines>...

        allow_nonexistent=allow_nonexistent,

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/watcher/event_based_path_watcher.py", line 185, in watch_path

    folder_handler.watch = self._observer.schedule(

                           ~~~~~~~~~~~~~~~~~~~~~~~^

        folder_handler, folder_path, recursive=True

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/home/adminuser/venv/lib/python3.13/site-packages/watchdog/observers/api.py", line 312, in schedule

    emitter.start()

    ~~~~~~~~~~~~~^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/watchdog/utils/__init__.py", line 75, in start

    self.on_thread_start()

    ~~~~~~~~~~~~~~~~~~~~^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start

    self._inotify = InotifyBuffer(path, recursive=self.watch.is_recursive, event_mask=event_mask)

                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/watchdog/observers/inotify_buffer.py", line 30, in __init__

    self._inotify = Inotify(path, recursive=recursive, event_mask=event_mask)

                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/watchdog/observers/inotify_c.py", line 149, in __init__

    Inotify._raise_error()

    ~~~~~~~~~~~~~~~~~~~~^^

  File "/home/adminuser/venv/lib/python3.13/site-packages/watchdog/observers/inotify_c.py", line 438, in _raise_error

    raise OSError(errno.EMFILE, "inotify instance limit reached")

OSError: [Errno 24] inotify instance limit reached

Exception ignored in: <function AppSession.__del__ at 0x7f377afe6340>

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/app_session.py", line 178, in __del__

    self.shutdown()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/app_session.py", line 255, in shutdown

    self.request_script_stop()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/app_session.py", line 429, in request_script_stop

    if self._scriptrunner is not None:

AttributeError: 'AppSession' object has no attribute '_scriptrunner'

2025-07-30 16:31:44.870 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec

    exec(code, module.__dict__)  # noqa: S102

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/civitas_streamlit/app.py", line 4, in <module>